# Generated by Django 5.0 on 2024-02-14 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0003_feedback'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='feedback',
            table='FeedBack',
        ),
    ]
