# Generated by Django 5.0 on 2024-02-21 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0004_alter_feedback_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeedbackForm',
        ),
    ]
